version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y

      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            aws configure set aws_access_key_id AKIAICHTO2S3TG3C6ZMQ
            aws configure set aws_secret_access_key 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
            aws configure set default.region us-east-1

      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            ls -al
            mvn clean install
            cd target/
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            cd codedeploy_artifact
            cp ../infrastructure/aws/codedeploy/*.sh .
            cp ../*.yml .
            cp ../webapp/target/webApp-0.0.1-SNAPSHOT.jar .
            cp ../webapp/src/main/resources/*.properties .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip .
            rm *.yml *.sh *.properties *.jar
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp --recursive codedeploy_artifact s3://code-deploy.csye6225-spring2019-gadhiyah.me
      - run:
          name: Make CodeDeploy API call
          command: |
            aws deploy create-deployment --output json --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --s3-location bucket=code-deploy.csye6225-spring2019-gadhiyah.me,bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
